name: Docker Build Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes/merges to the 'main' branch

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # Path to the Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest
