name: Test Coverage & Code Analysis

on:
  push:
    branches:
      - develop  # Trigger on pushes to the 'develop' branch
  pull_request:
    branches:
      - develop  # Trigger on pull requests targeting the 'develop' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project and run unit tests
      - name: Build and test with Maven
        run: mvn clean verify  # This will run tests as well as generate coverage reports

      # Step 5: Run PMD analysis (code quality)
      - name: Run PMD Analysis
        run: mvn pmd:check  # Runs PMD static analysis

      # Step 6: Upload coverage results (Jacoco)
      - name: Upload Jacoco coverage report
        if: success()  # Only upload if the build and tests are successful
        uses: codecov/codecov-action@v3
        with:
          file: target/jacoco-ut/jacoco.xml  # Adjust if your report is in a different location
